# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TiDB Blog
tagline:          'TiDB Blog'
description:      'TiDB is a distributed SQL database. Inspired by the design of Google F1, TiDB supports the best features of both traditional RDBMS and NoSQL.'
url:              http://github.io/pingcap/blog
baseurl:          ""
excerpt_separator: "<!--more-->"

author:
  name:           'PingCAP'
  url:            https://www.pingcap.com

paginate:         5

# Custom vars
github:
  repo:           https://github.com/pingcap/tidb

weekly:
  url:            http://weekly.pingcap.com

